// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
with inserted_feed_follow as (
	INSERT INTO feeds_follow(id, created_at, updated_at, user_id, feed_id)
	VALUES (
		$1,
		$2,
		$3,
		$4,
		$5
	)
	returning id, created_at, updated_at, user_id, feed_id
)
SELECT
	inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.user_id, inserted_feed_follow.feed_id,
	feeds.name AS feed_name,
	users.name AS user_ame
FROM
	inserted_feed_follow
INNER JOIN
	users ON inserted_feed_follow.user_id = users.id
INNER JOIN
	feeds ON inserted_feed_follow.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserAme   string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserAme,
	)
	return i, err
}

const deleteFeedFollow = `-- name: DeleteFeedFollow :exec
DELETE FROM
  feeds_follow
WHERE
  id IN (
    SELECT
      feeds_follow.id
    FROM
      feeds_follow
    INNER JOIN
      feeds ON feeds_follow.feed_id = feeds.id
    INNER JOIN
      users ON feeds_follow.user_id = users.id
    WHERE
      users.id = $1 AND feeds.id = $2
  )
`

type DeleteFeedFollowParams struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

func (q *Queries) DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollow, arg.ID, arg.ID_2)
	return err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT users.name, feeds.name
FROM
	users
INNER JOIN
	feeds_follow on users.id = feeds_follow.user_id
INNER JOIN
	feeds on feeds.id = feeds_follow.feed_id
where users.name = $1
`

type GetFeedFollowsForUserRow struct {
	Name   string
	Name_2 string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, name string) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(&i.Name, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveFeedUser = `-- name: RetrieveFeedUser :one
SELECT users.name FROM users
WHERE users.id IN (
	SELECT feeds.user_id FROM feeds
	WHERE feeds.name = $1
)
`

func (q *Queries) RetrieveFeedUser(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, retrieveFeedUser, name)
	err := row.Scan(&name)
	return name, err
}
